services:
  archivebackend:
    image: ghcr.io/exceptionhandlersuoa/nostalgia-backend:latest
    container_name: archivebackend
    restart: unless-stopped
    ports:
      - 4273:8080
x-dockge:
  urls:
    - archivebackend.xyz.com
networks: {}
